apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-fastapi
  template:
    metadata:
      labels:
        app: hello-fastapi
    spec:
      containers:
        - name: hello-fastapi
          image: gabriel6garcia/hello-fastapi:latest:09beb31fead2566042ff4b4c75e04a6fa954e906
          ports:
            - containerPort: 80
