apiVersion: v1
kind: Service
metadata:
  name: argocd-server-http
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
